name: bmi_calculator
description: Bmi Calculator - Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  toggle_switch: ^2.1.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.11
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    # - assets/images/arrow.png

# https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21